before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/client/client.go
    id: client
    ldflags:
      - -s -w -X dyndns/internal.BuildVersion={{.Version}} -X dyndns/internal.CommitHash={{.ShortCommit}} -X dyndns/internal.BuildTime={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - openbsd
    goarch:
      - amd64
  - main: ./cmd/server/server.go
    id: server
    ldflags:
      - -s -w -X dyndns/internal.BuildVersion={{.Version}} -X dyndns/internal.CommitHash={{.ShortCommit}} -X dyndns/internal.BuildTime={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
